name: builder-small

on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'


env:
  CONTAINER_REGISTRY: docker.io
  
defaults:
  run:
    shell: bash
jobs:
  container_build:
    strategy:
      matrix:
        component: [ "hats",  "left-arm",  "left-leg",  "main",  "right-arm",  "right-leg" ]
        version: [ "v1", "v2", "v3", "v4" ]
    runs-on: ubuntu-20.04
    env:
      BRANCH: ${{ needs.prepare_ci_run.outputs.BRANCH }}
      VERSION: ${{ needs.prepare_ci_run.outputs.VERSION }}
      DATETIME: ${{ needs.prepare_ci_run.outputs.DATE }}${{ needs.prepare_ci_run.outputs.TIME }}
      GIT_SHA: ${{ needs.prepare_ci_run.outputs.GIT_SHA }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release-*' }}
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secretS.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VERSION=${{ matrix.version }}
          context: podtato-services-small/${{ matrix.component }}/.
          push: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release-*' }}
          file: podtato-services/${{ matrix.component }}/docker/Dockerfile
          platforms: linux/amd64
          tags: |
            ${{ env.CONTAINER_REGISTRY }}/vr00mm/podtato-${{ matrix.component }}:${{ matrix.version}}-latest
